blank_issues_enabled: false
contact_links:
    - name: ioBroker Community
      url: https://forum.iobroker.net/topic/82155/test-adapter-openmediavault
      about: Please ask and answer questions here.
